export const UPDATE_TOTAL_AMOUNT = 'UPDATE_TOTAL_AMOUNT'
export const ENABLE_LOADER = 'ENABLE_LOADER'
export const DISABLE_LOADER = 'DISABLE_LOADER'
export const ENABLE_FREE_SHIPPING = 'ENABLE_FREE_SHIPPING'
